apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-classifier-gpu
  namespace: aszen-ai-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-classifier-gpu
  template:
    metadata:
      labels:
        app: ai-classifier-gpu
    spec:
      containers:
        - name: ai-classifier-gpu
          image: 192.168.1.52:8082/ai-classifier-gpu:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: "1"
